CREATE TABLE IF NOT EXISTS product (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255),
    price DOUBLE PRECISION NOT NULL,
    available_stock BIGINT NOT NULL,
    last_update_date DATE DEFAULT CURRENT_DATE,
    FOREIGN KEY (id) REFERENCES product(id)
);

-- CREATE TABLE IF NOT EXISTS product_supplier (
--     product_id BIGINT NOT NULL,
--     supplier_id BIGINT NOT NULL,
--     PRIMARY KEY (product_id, supplier_id),
--     FOREIGN KEY (product_id) REFERENCES product(id),
--     FOREIGN KEY (supplier_id) REFERENCES supplier(id)
-- );


INSERT INTO product (name, category, price, available_stock) VALUES
    ('Widget A', 'Electronics', 19.99, 100),
    ('Book B', 'Books', 29.99, 50),
    ('Clothing C', 'Clothing', 39.99, 75);
