CREATE TABLE IF NOT EXISTS supplier (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    address_id BIGINT NOT NULL,
    phone_number VARCHAR(255) DEFAULT 'default_value',
    FOREIGN KEY (address_id) REFERENCES address(id)
);

CREATE TABLE IF NOT EXISTS product_supplier (
    supplier_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    PRIMARY KEY (supplier_id, product_id),
    FOREIGN KEY (supplier_id) REFERENCES supplier(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);


INSERT INTO supplier (name, address_id, phone_number) VALUES
    ('Acme Corp', 1, '123-456-7890'),
    ('Globex Inc.', 2, '987-654-3210'),
    ('Initech Ltd.', 3, '555-555-5555');
