version: '3.8'
services:
  app:
    image: sparrvio/myshop:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/lightShopApi
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: lightShopApi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 5s
        timeout: 5s
        retries: 5
#    volumes:
#      - postgres-data:/var/lib/postgresql/data # Для сохранения данных
    ports:
      - "5436:5432"

volumes:
  postgres-data: